<?php
/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Magento\Framework\Escaper $escaper */

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$scopeConfig = $objectManager->get(\Magento\Framework\App\Config\ScopeConfigInterface::class);

// Get selected theme and custom CSS
$selectedTheme = $scopeConfig->getValue('admintheme/general/theme_select', \Magento\Store\Model\ScopeInterface::SCOPE_STORE);
$customCss = $scopeConfig->getValue('admintheme/general/custom_css', \Magento\Store\Model\ScopeInterface::SCOPE_STORE);

$themeFile = false;
if ($selectedTheme === 'light') {
    $themeFile = 'DevScripts_AdminTheme::css/light-styles.css';
} elseif ($selectedTheme === 'dark') {
    $themeFile = 'DevScripts_AdminTheme::css/dark-styles.css';
}
?>

<?php if ($themeFile): ?>
    <link rel="stylesheet" type="text/css" href="<?= $escaper->escapeHtmlAttr($block->getViewFileUrl($themeFile)) ?>" />
<?php endif; ?>

<?php if ($customCss): ?>
    <style><?= /* @noEscape */ $customCss ?></style>
<?php endif; ?>